### ISSUE TITLE
Demo UI should not require internet access

### ISSUE THREAD

**Issue by alsz** [cadets/cadets-ui#10]
The demo currently pulls a number of javascript files and icons down when the page is loaded. Most, if not all, should be added locally so that the ui will load even without internet access.

**Remaining:**
- [x] machine icon (from wikimedia)
- [ ] Roboto font (from fonts.googleapis.com)

**Comment by trombonehero** [comment]
Marking this as a bug, since a lack of Internet access could cause demo gremlins.

**Comment by trombonehero** [comment]
What remains:

- [ ] machine icon (from wikimedia)
- [ ] Roboto font (from fonts.googleapis.com)

**Comment by trombonehero** [comment]
Commit 106d949 closes out this issue.
