### ISSUE TITLE
Ability to add successors to worksheet

### ISSUE THREAD

**Issue by trombonehero** [cadets/cadets-ui#11]
The context menu for a node in the worksheet should include functionality to add all successor nodes (in terms of provenance) to the same worksheet.

**Comment by trombonehero** [comment]
To get started on this one, it could be helpful to look at the `attach_context_menu` function defined in [static/js/graphing.js](/cadets/cadets-ui/blob/master/playground/static/js/graphing.js#L37) and where it's called from [templates/worksheet.html](/cadets/cadets-ui/blob/master/playground/templates/worksheet.html#L114). You'll need to add a new function with the same signature as `inspect` or `import_into_worksheet`... in fact, some of the JSON fetching/iteration code in `inspect` and  `import_into_worksheet` could be a good model for the new functionality. You may find that you can rely on calling `import_into_worksheet` from your code, but some other refactoring might make more sense.

**Comment by trombonehero** [comment]
Also, the OPUS query parts can be found in [/srv/opus-console-srv.py](/cadets/cadets-ui/blob/master/srv/opus-console-srv.py#L162). While we're running the playground as a separate "branch", we probably just want to copy that query into our server.

**Comment by HarkonenBade** [comment]
Successors query from /srv/opus-console-srv.py is now in the playground server. It should be accessible at `/successors/<dbid>` It accepts a single get param `max_depth` defining how deep in the graph to search back, this defaults to 4 hops.

**Comment by trombonehero** [comment]
Is there a value of `max_depth` that means "without limit"? An attack could involve a lot of steps (e.g., file versions) without necessarily involving a lot of branching (and therefore a lot of nodes).

"There isn't such a value" would be a fine answer, as we can always ask for some large number, or iteratively ask for another N levels.

**Comment by HarkonenBade** [comment]
There is no such value in the current implementation. One could be added if desired.

**Comment by trombonehero** [comment]
Ok, thanks to @alsz in #17 we can now add successors... and there are a **lot** of them. :)

I wonder if we might want a couple of variants of the "successors" query, e.g., one that adds everything and one that only adds successors in the process tree (but not file-version nodes)?

**Comment by trombonehero** [comment]
At the very least, this would be a nice place to expose the distinction between provenance edges that we are sure about vs those we infer "just in case" (as when we unlink files twice and label the edge `RaW` just in case).

**Comment by trombonehero** [comment]
Successor filtering now works (see #7), so this works too!
