### ISSUE TITLE
Show files as well as versions

### ISSUE THREAD

**Issue by trombonehero** [cadets/cadets-ui#15]
When we import a file-version into the worksheet, we should break it down as a parent file (with a UUID) and child versions.

**Comment by HarkonenBade** [comment]
Would supporting this be a good first step to collapsing version in the graph helpfully? If so what data would you need on the parent node? Our initial thoughts were uuid, hostuuid and the union of the names of the versions. Also can cytoscape handle giving the parent node the union of it's children's edges in the right situation, or would we also need to emit these?

**Comment by trombonehero** [comment]
As a first cut, I think that the abstract file objects can be generated entirely dynamically in JavaScript: I'll add files to the graph using the file UUID as an ID and the file-version `host` field as a parent for the file. I can then add a `names: new Set()` field to the abstract file node's scratch data. So, maybe no OPUS changes required...

**Comment by HarkonenBade** [comment]
Roger, update if you find things that are needed.

**Comment by trombonehero** [comment]
Resolved by acea897.
