### ISSUE TITLE
Linking Machine View to Worksheet View

### ISSUE THREAD

**Issue by HarkonenBade** [cadets/cadets-ui#16]
- [x] Clicking on an internal machine swaps to worksheet view with a filter for only nodes on that host
- [ ] Clicking on an external machine swaps to worksheet view with a filter for only connections to that IP

**Comment by trombonehero** [comment]
5edbde19b86ba09722f9a501da5ea598aece2ed5 will help with this. Now we just need more filters as described in #13 and we should be able to close this issue out too.

**Comment by trombonehero** [comment]
The second part of this probably depends on #18.

**Comment by trombonehero** [comment]
Actually, since machines can have multiple IPs, the current approach of pre-loading the machine in the Inspector (from which we can see connections to sockets) might make the most sense for point 2.
