### ISSUE TITLE
UI Stylistic Notes

### ISSUE THREAD

**Issue by HarkonenBade** [cadets/cadets-ui#21]
- [ ] Scrolling in the node list should probably not scroll the rest of the window. As otherwise by the time you have scrolled particularly far down the rest is out of sight.
- [x] More spacing between the id, icon and name in the nodes view would work better, as particularly process icons get lost in the names and just look like preceding underscores.
- [x] Is showing the DB ids in the node view really helpful?
- [x] Changing the filters on the inspector should probably refresh it.

**Comment by trombonehero** [comment]
I think that I'll call this issue complete on the grounds that "three out of four ain't bad". The first point (not scrolling too far) can probably be addressed with some combination of CSS and jQuery, but I think we'll leave it off for this demo.
