### ISSUE TITLE
Process missing from neighbours query

### ISSUE THREAD

**Issue by trombonehero** [cadets/cadets-ui#24]
Using the `gcj-db` DB from yesterday and commit efd81bef1385a5aa6c01cadf78f347bec4fb7ad1, the following query endpoint produces no results:

`http://localhost:5001/neighbours/9c406dd7-fb67-475d-a716-6f25cf331916:d6bba606-5cac-11e7-a0ee-080027d14c67?files=false&sockets=true&process_meta=true`

The node in question is an `sshd` process whose only neighbours are files. When we filter out files, I had expected to still see the node being queried, as processes should never be filtered out.

**Comment by alsz** [comment]
I think this is because the inspector graph is based on the neighbours query. Normally the neighbours query returns the root node as well, but if there's no neighbours, it doesn't return any nodes. Thus, nothing is displayed.

**Comment by trombonehero** [comment]
Indeed, that's the bug. :)

We can work around it by doing a separate query for the root node if the neighbours query comes back empty, but I'm hoping it won't take much to change the query such that "X and its neighbours" returns X by itself when there are no neighbours. If that's any amount of work then we can do the workaround instead.

**Comment by HarkonenBade** [comment]
I'll take a look, but the main problem is that the given DB query we are executing does return no entries if there are no neighbours of that node. If you are running the inspector window for a node, surely you have that nodes data already? Probably from executing /nodes?
