### ISSUE TITLE
Visual Tweaks to UI

### ISSUE THREAD

**Issue by HarkonenBade** [cadets/cadets-ui#45]
- [x] Colouring of grouped connections may be unclear.
- [x] Show links between neighbours in inspector - @harkonenbade
- [x] CADETS/OPUS on top left
- [x] Maybe have show commands from process - @harkonenbade
- [x] All the files that were read popup - @harkonenbade
- [x] UI colours better chosen for things like R/G colour blindness
- [x] Socket version grouped
- [x] OPUS - Elide `<unknown>` values - @harkonenbade
- [x] Ensure machine names are visible - either by moving name or padding nodes

**Comment by HarkonenBade** [comment]
Done my bits of number 4

**Comment by HarkonenBade** [comment]
Done my bits of number 5

**Comment by trombonehero** [comment]
All done!
