### ISSUE TITLE
When Inspector inspects a node with a large amount of connections the GUI will lag for a while

### ISSUE THREAD

**Issue by gk3758** [cadets/cadets-ui#68]
Should this be solved by limiting the number of nodes shown or show some indication that it is loading or some other way? @trombonehero 

To trigger in NodeSearchsheet Type process, Name cron, then select "14:00h 8 May cron"

**Comment by trombonehero** [comment]
I suppose that we might start by asking Neo4j how many edges a node participates in, and then choose whether to load them all at once or in batches based on some threshold value. That approach assumes that calculating `count(edges)` is significantly (i.e., at least an order of magnitude) faster than actually querying all of the neighbours' details... that's an empirical question that we might want to find the answer to. :)

**Comment by gk3758** [comment]
It was decided that the number of nodes shown in the Inspector window will be limited to an amount a user would find meaningful. All nodes will still be shown in the Neighbors window and the Inspector window will warn the user that only x of y nodes are currently being shown. Possibly include a way to iterate through the hidden nodes in the Inspector window.
