### ISSUE TITLE
OPUS query: successors

### ISSUE THREAD

**Issue by trombonehero** [cadets/cadets-ui#7]
It would be nice (though not *immediately* required) if the UI could ask OPUS, "what are all of the provenance successors of node `x`?"

**Comment by trombonehero** [comment]
It seems like this is now working and maybe complete?

**Comment by trombonehero** [comment]
From #11:

> I wonder if we might want a couple of variants of the "successors" query, e.g., one that adds everything and one that only adds successors in the process tree (but not file-version nodes)?

I tried something like this out locally and it seemed to help make the story a bit more believable. I can try to take a cut at this but some query review will probably be required. :)

**Comment by trombonehero** [comment]
Actually, perhaps the successors query should accept the same filtering arguments as the neighbours query now does?

**Comment by trombonehero** [comment]
It looks like 2f151c6fb2f7c9f18bc12b3cc862a927e05102cc almost takes care of this. I still have a stray socket version showing up when I look at 34f39864-52a3-413b-8ad0-34044684dfe1:04cfd180-5acd-11e7-813e-080027d14c66:

<img width="345" alt="screen shot 2017-06-28 at 1 32 24 pm" src="https://user-images.githubusercontent.com/85833/27647553-52517c8a-5c06-11e7-883c-ed253271ffef.png">

**Comment by HarkonenBade** [comment]
hmm, I do not observe this behaviour. Have you made sure that your caches are purged and that you are using the latest database version?

**Comment by trombonehero** [comment]
Unable to reproduce with recent code and data, closing
