### ISSUE TITLE
Make sure that Inspector -> Details windows is showing the correct date

### ISSUE THREAD

**Issue by gk3758** [cadets/cadets-ui#70]
@trombonehero I was wondering if the timestamp that is shown in Inspector -> Details window is the correct date.

**Comment by trombonehero** [comment]
In the database I'm using:

```
$ shasum -a 512 gnn.zip
cc1bd1f205c20c0c0f86d7cc73791cad80d245340105d4199b495d7ea392adebc9cf11c0e63db082ab23ac5975b598448452850fe8425449b2a0dd98115636a3  gnn.zip
```

I see timestamps around 9:30–10pm on 26 Jun, which (if 2017) sounds maybe close to correct (that was around the run-up to the PI meeting where we did our big exciting demo). We should revisit this once we have fresh traces to analyze.
