### ISSUE TITLE
When importing nodes if the correct filter isn't selected the edge will not load

### ISSUE THREAD

**Issue by gk3758** [cadets/cadets-ui#73]
To trigger in NodeSearchsheet Type socket-version next select any node. In the Inspector window Sockets filter isn't selected. Then Individually import each neighbor socket

![image](https://user-images.githubusercontent.com/25505147/36595332-594feeee-187c-11e8-8b77-d703a5d3879a.png)

How should this be sorted out? should a warning be given to the user or is this the desired result of not have the filter selected. @trombonehero

**Comment by trombonehero** [comment]
I think that the filters in the Inspector window should only apply to nodes, and then only to filter which neighbours of the "node under inspection" will be:

1. shown in the Inspector and/or
2. imported into a worksheet via "Import Neighbours".

So, the filters should not affect which nodes can be manually inspected, nor should they affect which edges are displayed in a worksheet. I had thought (though I may be mistaken) that the logic for importing nodes into the worksheet had been:

 * compute the set `E` of existing nodes in the graph
 * add the set `N` of new nodes to the graph
 * ask Neo4j for all edges among nodes in `N`; add to graph
 * ask Neo4j for all edges between nodes in `N` and nodes in `E`; add to graph

So, if we agree that's the right algorithm (insert discussion here), there may be an implementation issue with the code that was supposed to implement it.

Thoughts?
