### ISSUE TITLE
OPUS query: filter PCAP (or 4-tuples) by host provenance

### ISSUE THREAD

**Issue by trombonehero** [cadets/cadets-ui#8]
As discussed on this morning's call, the UI needs to be able to ask OPUS, "which of the connections in set `cs` includes data from any of the hosts in set `hs`?"

Depending on how the time goes, this pre-filtering step might actually happen via a command-line UI rather than the GUI. If that's the case, a worked example of such a command-line UI might be helpful.

**Comment by HarkonenBade** [comment]
Is this now done?

**Comment by trombonehero** [comment]
This issue was replaced by the Bro notification story.
