### ISSUE TITLE
Server code duplication

### ISSUE THREAD

**Issue by lc525** [cadets/cadets-ui#9]
From the latest series of commits, 76fec69 d047877 and d46b97a seem to duplicate code written in the opus web server. If there are problems with the original code, we would like to fix them so that things are usable on the UI side; If quick changes are required, they can also be made directly by adjusting that code. However, duplicating code makes inefficient use of time on both sides. 

Compared to what's currently in playground, the functionality on our side is a bit more mature, with options for record/replay (including GET arguments). However, the framework used is exactly the same (the code in playground should have been trivial to port, but perhaps there was a blocking issue we weren't aware of?). It's not a problem at all if we decide to go and modify the playground code from now on, but it's a matter that should be discussed.

We were intending to continue adding queries and features (i.e for processing pcap files) to our end, but given the latest series of commits we're unsure on how to proceed.

Moving forward, I see two options:

- we port over changes made in playground which fork our code and remove any other blocking issues.
- work is continuing on the playground directory and the opus team redirects resources towards helping the demo in other ways, including adding all future contributions to /playground.

**Comment by trombonehero** [comment]
I see the "playground" directory as something of a feature branch on which I can iterate rapidly and then (likely after the demo) fold changes back into the pre-existing OPUS UI. I found that there were dependencies in the existing code that would have required more "faulting in" than is needed to directly support the demo, but on the other hand I don't see any reason to throw away all of that work (which, as you say, supports things like record/replay that "playground" doesn't).

**Comment by trombonehero** [comment]
I'm going to close this issue, as the new codebase actually obviates the need for any server-side code.
